name: mood_prints
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  country_picker: ^2.0.26
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  pinput: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  syncfusion_flutter_charts: ^27.1.52
  table_calendar: ^3.1.2
  #
  fluttertoast: ^8.2.10
  http: ^1.2.2
  shared_preferences:
  connectivity_plus: ^6.1.1
  loading_animation_widget: ^1.3.0 
  image_picker: ^1.1.2
  emoji_picker_flutter: ^4.2.0
  get_storage: ^2.1.1
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.0
  uuid: ^4.5.1
  percent_indicator: ^4.2.4
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  # firebase_messaging: ^15.2.1
  firebase_messaging: 


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ""
